export { default as AppMain } from '@/layout/components/AppMain.vue'
export { default as Navbar } from '@/layout/components/Navbar.vue'
export { default as Settings } from '@/layout/components/Settings/index.vue'
export { default as Sidebar } from '@/layout/components/Sidebar/index.vue'
export { default as TagsView } from '@/layout/components/TagsView/index.vue'